spring:
  datasource:
    url: jdbc:postgresql://ep-fragrant-thunder-a1slsc5r-pooler.ap-southeast-1.aws.neon.tech:5432/verceldb
    username: default
    password: 8uaJ7mPKhgXl
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      secret-key: ES50/67VPIWrjrvU8LfTIglKGlW8XVe6tw74BxwK4mnehYxV1YxxlSRw/EyoPR6RIYPJ7U8/aylqCfAFofA4rcCL05sts4uFuhhyzxlhRGAO8K1UchSXb15lgquXm5TXTO9IrN2X5VGS+M02iEf5jjItHd1uMKCCODNRPJraTKAEjxkZWxk2tCLDcT85q24uhY6WpExJ0Or4f31VFNr4+oaMlAGdHBzuP23q4p9pxhcsylorQpktDh52UD9Xoswe76SMqJIW3PYreaBFPIAzWyST6pC17xFagrqAEU/ysvFEsUWnJJVsxNGy+o6lQQStpK0cMPMxQm5NfjoEaeuBxYcnbYahZ8ASP8TRZ1/SWkg=
      expiration: 600000 #One day
      refresh-token:
        expiration: 604800000 # Seven days